<a href="https://colab.research.google.com/github/chrismallqui/python_total_machine_learning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [1]:
# Pandas es una biblioteca de software libre escrita para el lenguaje de programación
# Python, diseñada específicamente para la manipulación y el análisis de datos.
# Proporciona estructuras de datos de alto rendimiento y herramientas de análisis fáciles de usar.
import pandas as pd

In [15]:
# Datos representados en un diccionario de listas
datos = {"nombre": ["Pedro", "Juan", "Lorena"],
         "edad": [25, 39, 33]}

print(datos)

{'nombre': ['Pedro', 'Juan', 'Lorena'], 'edad': [25, 39, 33]}

In [16]:
# Un DataFrame es la estructura de datos principal de Pandas. Es una tabla bidimensional
# de datos etiquetados en filas y columnas, equivalente a una hoja de cálculo de Excel
# o a una tabla de base de datos relacional (SQL).
# Creación del Dataframe
df = pd.DataFrame(datos)

print(df)

   nombre  edad
0   Pedro    25
1    Juan    39
2  Lorena    33

In [6]:
# Verificación del tipo de objeto del elemento completo 'df'
# Confirma que la variable es una estructura bidimensional de tipo DataFrame
# (pandas.core.frame.DataFrame)
type(df)

pandas.core.frame.DataFrame

In [8]:
# Acceso a una columna mediante corchetes
df["nombre"]

0     Pedro
1      Juan
2    Lorena
Name: nombre, dtype: object

In [9]:
# Acceso a una columna como atributo del DataFrame
df.nombre

0     Pedro
1      Juan
2    Lorena
Name: nombre, dtype: object

In [10]:
# Verificación del tipo de objeto:
# extrae una única columna devuelve una Pandas Series
type(df.nombre)

pandas.core.series.Series

## Limpieza de datos

In [18]:
# La limpieza de datos (data cleaning) en Pandas es el proceso de detectar, corregir
# o eliminar errores, inconsistencias, valores nulos o duplicados dentro de un conjunto
# de datos (Dataframe) para garantizar que los datos seanprecisos, completos y listos
# para análisis o aprendizaje automático.
data = {"id_producto": [1001, 1002, 1003, 1003],
        "cantidad_vendida": [30, None, 25, 25],
        "precio": [20.5, 15.0, None, 22.5]}

In [19]:
df = pd.DataFrame(data)

# Mostrar los primeros 5 elementos
df.head()

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [20]:
# Muestra un resumen general del DataFrame: tipos de datos, total de filas, columnas y memoria utilizada.
# Permite identificar de un vistazo cuántos valores nulos hay en cada columna
# (comparando 'non-null' contra el total de entradas)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_producto       4 non-null      int64
 1   cantidad_vendida  3 non-null      float64
 2   precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [21]:
# Evalúa cada celda del DataFrame para detectar valores nulos o faltantes (NaN/None)
# Devuelve una máscara booleana (True si el valor es nulo, False si contiene datos)
df.isnull()

   id_producto  cantidad_vendida  precio
0        False             False   False
1        False              True   False
2        False             False    True
3        False             False   False

In [22]:
# # Cuenta la cantidad total de valores nulos o faltantes (NaN/None) presentes en cada columna del DataFrame
# Suma los valores booleanos True (1) generados por .isnull() para dar el conteo final por columna
df.isnull().sum()

id_producto         0
cantidad_vendida    1
precio              1
dtype: int64